version: "3.9"

x-refs:
  djangoconf:
    &djangoconf
    env_file: .env.example
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      maildev:
        condition: service_healthy
    volumes:
      - .:/app
services:
  django:
    <<: *djangoconf
    command: "ci"
    depends_on:
      celery:
        condition: service_healthy
  celery:
    <<: *djangoconf
    command: "celery"
    healthcheck:
      test: [ "CMD-SHELL", "make celery-healthcheck" ]
      start_period: 2s
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: "postgres:latest"
    restart: on-failure
    env_file: .env.example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:latest"
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  maildev:
    image: "soulteary/maildev:latest"
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      - MAILDEV_INCOMING_USER=dev
      - MAILDEV_INCOMING_PASS=dev
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1080" ]
      start_period: 2s
      interval: 10s
      timeout: 5s
      retries: 5
